tv/blog/urls.py
from django.conf.urls import url
from django.contrib import admin 
from django.urls import path ,include
from .views import  blog_Cntnt
from . import views


app_name = 'blog'


urlpatterns = [
    path('', views.blog_Cntnt, name='blog_Cntnt'),
    path('<str:cntnt_slug>/', views.blog_Cntnt, name='details'),
    path('pp/<str:blog_cntnt_dtls>/', views.blog_Cntnt, name='sub_details'),
    path('<str:category_slug>/', views.product_list, name='product_list_by_category'),
    #path('<int:id>/<str:slug>/', views.product_detail, name='sub_product_list'),
]

tv/detaset/blog/urls.py
from django.conf.urls import url
from django.contrib import admin 
from django.urls import path ,include
from .views import  blog_Cntnt
from . import views


app_name = 'blog'


urlpatterns = [
    path('', views.blog_Cntnt, name='blog_Cntnt'),
    path('<str:cntnt_slug>/', views.blog_Cntnt, name='details'),
    path('pp/<str:blog_cntnt_dtls>/', views.blog_Cntnt, name='sub_details'),
    #path('<str:category_slug>/', views.product_list, name='product_list_by_category'),
    #path('<int:id>/<str:slug>/', views.product_detail, name='sub_product_list'),
]

tv/package/urls.py
from django.conf.urls import url
from django.contrib import admin 
from django.urls import path ,include
from .views import  product_list
from . import views

app_name = 'package'


urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('category/<str:category_slug>/', views.product_list, name='product_list_by_category'),
    path('detail/<int:id>/<str:slug>/', views.product_detail, name='sub_product_list'),
    path('category_them/<str:them_slug>', views.product_list, name='theme_product_list'),
    path('category_price/<str:price_slug>', views.product_list, name='price_product_list'),
    path('category_offer/<str:offer_slug>', views.product_list, name='offer_product_list'),
    path('category_destination/<str:cat_slug>', views.product_list, name='cat'),
]



    # path(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    # path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='sub_product_list'),

tv/tv/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('package.urls')),
    path('blog/', include('blog.urls')),
    path('form/', include('form.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tv/blog/models.py
from django.db import models
from django.urls import reverse
from package.models import Product
class Cntnt(models.Model):
    product = models.ForeignKey(Product, related_name='product_del',verbose_name=('product') ,on_delete=models.CASCADE)
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(max_length=300, db_index=True)
    desc1=models.CharField(max_length=150, db_index=True)
    desc1=models.CharField(max_length=150, db_index=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'cntnt'
        verbose_name_plural = 'cntnts'
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:list_by_cntnt', args=[self.name])
    def get_absolute_url_p(self):
        return reverse('blog:details',args=[self.product])
    def get_absolute_url_sub_product(self):
        return reverse('blog:sub_details',args=[self.slug])   

# Create your models here.

tv/detaset/blog/models.py
from django.db import models
from django.urls import reverse
from package.models import Product
class Cntnt(models.Model):
    product = models.ForeignKey(Product, related_name='product_del',verbose_name=('product') ,on_delete=models.CASCADE)
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(max_length=300, db_index=True)
    desc1=models.CharField(max_length=150, db_index=True)
    desc1=models.CharField(max_length=150, db_index=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'cntnt'
        verbose_name_plural = 'cntnts'
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:list_by_cntnt', args=[self.name])
    def get_absolute_url_p(self):
        return reverse('blog:details',args=[self.product])
    def get_absolute_url_sub_product(self):
        return reverse('blog:sub_details',args=[self.slug])   

# Create your models here.

tv/blog/views.py
from django.shortcuts import render
from .models import Cntnt
from package.models import Product
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from django.views.generic import TemplateView
from package.views import  product_list

# Create your views here.
def blog_Cntnt(request,cntnt_slug=None,blog_cntnt_dtls=None):
	#product=Cntnt.product
	#name=Product.name
	slug=None
	cntnts = Cntnt.objects.all()
	cntnts1=Cntnt.objects.order_by('-created_at')[0:1]
	contxt={'cntnts':cntnts,
	'cntnts1':cntnts1
	}
	if cntnt_slug:
		product = get_object_or_404(Product, slug=cntnt_slug)
		# cntnts1=Cntnt.objects.filter(name=name)[0]
		#products=Product.objects.filter(slug=cntnt_slug)
		contxt={#'cntnts':cntnts,
		# 'cntnts1':cntnts1,
		'product':product
		}
		return render(request, 'product/details.html', contxt)
	elif blog_cntnt_dtls:
		cntnts1=Cntnt.objects.filter(slug=blog_cntnt_dtls)
		cntnts = Cntnt.objects.order_by('?')[0:3]
		contxt={'cntnts':cntnts,
		'cntnts1':cntnts1}
		return render(request, 'blog/blog_list.html', contxt)	
	else:
		return render(request, 'blog/blog_list.html', contxt)
"""def blog_cntnt_dtls(request,cntnt_slug):
	cntnt = get_object_or_404(Cntnt, id=id, slug=slug, available=True)
	#cart_product_form = CartAddProductForm()
	context = {
		 'cntnt': cntnt,
		#'cart_product_form': cart_product_form
	}
	return render(request, 'blog/blog_detls.html', context)""" 	
#def side_bar_views(request,sub_cntnt_slug=None):

tv/detaset/blog/views.py
from django.shortcuts import render
from .models import Cntnt
from package.models import Product
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from django.views.generic import TemplateView

# Create your views here.
def blog_Cntnt(request,cntnt_slug=None,blog_cntnt_dtls=None):
	#product=Cntnt.product
	#name=Product.name
	slug=None
	cntnts = Cntnt.objects.all()
	cntnts1=Cntnt.objects.order_by('-created_at')[0:1]
	contxt={'cntnts':cntnts,
	'cntnts1':cntnts1
	}
	if cntnt_slug:
		product = get_object_or_404(Product, slug=cntnt_slug)
		# cntnts1=Cntnt.objects.filter(name=name)[0]
		#products=Product.objects.filter(slug=cntnt_slug)
		contxt={#'cntnts':cntnts,
		# 'cntnts1':cntnts1,
		'product':product
		}
		return render(request, 'product/details.html', contxt)
	elif blog_cntnt_dtls:
		cntnts1=Cntnt.objects.filter(slug=blog_cntnt_dtls)
		cntnts = Cntnt.objects.order_by('?')[0:3]
		contxt={'cntnts':cntnts,
		'cntnts1':cntnts1}
		return render(request, 'blog/blog_list.html', contxt)	
	else:
		return render(request, 'blog/blog_list.html', contxt)
"""def blog_cntnt_dtls(request,cntnt_slug):
	cntnt = get_object_or_404(Cntnt, id=id, slug=slug, available=True)
	#cart_product_form = CartAddProductForm()
	context = {
		 'cntnt': cntnt,
		#'cart_product_form': cart_product_form
	}
	return render(request, 'blog/blog_detls.html', context)""" 	
#def side_bar_views(request,sub_cntnt_slug=None):

tv/detaset/blog/templates/product/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}tv{% endblock %}</title>
   
</head>
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="50">
{% include 'product/navbar.html' %}


{% block content %}


{% endblock %}

{% include 'product/footer.html' %}
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
</body>
</html>

tv/detaset/blog/templates/product/details.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Products{% endblock %}</title></head>
    <body>
   <ul>
	
		<h1>{{product.description}}</h1>
		<h1>sadsd</h1>

	
	</ul>

</body>
</html>

tv/detaset/blog/templates/product/footer.html
{% block footer %}  
    <footer class="site-footer">
 <div class="container-fluid">
 	<div class="row">
 	</div>
 </div>
      
</footer>{% endblock %}

tv/detaset/blog/templates/product/mainlist.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Products{% endblock %}</title></head>
    <body>
    	{% include 'product/navbar.html' %}
   <ul>
	{% for product in products %}
	<a href="{{product.get_absolute_url}}">
		<h1>{{product.price}}</h1></a>

	{% endfor %}
	</ul>
{% include 'product/search.html' %}
</body>
</html>

tv/detaset/blog/templates/product/message.html
message.html

tv/detaset/blog/templates/product/navbar.html
{% load static %}
{% load staticfiles %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <style>
  body {
    font: 400 15px/1.8 Lato, sans-serif;
    color: #777;
  }
  h3, h4 {
    margin: 10px 0 30px 0;
    letter-spacing: 10px;      
    font-size: 20px;
    color: #111;
  }
  .container {
    padding: 80px 120px;
  }
  .person {
    border: 10px solid transparent;
    margin-bottom: 25px;
    width: 80%;
    height: 80%;
    opacity:0.8;
  }
  .person:hover {
    border-color: #f1f1f1;
  }
  .carousel-inner img {
    -webkit-filter: grayscale(90%);
    filter: grayscale(90%); /* make all photos black and white */ 
    width: 100%; /* Set width to 100% */
    margin: auto;
  }
  .carousel-caption h3 {
    color: #fff !important;
  }
  @media (max-width: 600px) {
    .carousel-caption {
      display: none; /* Hide the carousel text when the screen is less than 600 pixels wide */
    }
  }
  .bg-1 {
    background: #2d2d30;
    color: #bdbdbd;
  }
  .bg-1 h3 {color: #fff;}
  .bg-1 p {font-style: italic;}
  .list-group-item:first-child {
    border-top-right-radius: 0;
    border-top-left-radius: 0;
  }
  .list-group-item:last-child {
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .thumbnail {
    padding: 0 0 15px 0;
    border: none;
    border-radius: 0;
  }
  .thumbnail p {
    margin-top: 15px;
    color: #555;
  }
  .btn {
    padding: 10px 20px;
    background-color: #333;
    color:#FD460F;
    border-radius: 0;
    transition: .2s;
  }
  .btn:hover, .btn:focus {
    border: 1px solid #333;
    background-color: #fff;
    color: #000;
  }
  .modal-header, h4, .close {
    background-color: #333;
    color: #fff !important;
    text-align: center;
    font-size: 30px;
  }
  .modal-header, .modal-body {
    padding: 40px 50px;
  }
  .nav-tabs li a {
    color: #777;
  } 
  .navbar {
    font-family: Montserrat, sans-serif;
    margin-bottom: 0;
    background-color: #314FA1;
    border: 0;
    font-size: 14px !important;
    letter-spacing: 6px;
    opacity: 0.8;
  }
  .navbar li a, .navbar .navbar-brand { 
    color: #d5d5d5 !important;
  }
  .navbar-nav li a:hover {
    color: #fd460f !important;
  }
  .navbar-nav li.active a {
    color: #fd460f !important;
    background-color: #FD460F !important;
  }
  .navbar-default .navbar-toggle {
    border-color: transparent;
  }
  .open .dropdown-toggle {
    color: #fff;
    background-color: #fd460f !important;
  }
  .dropdown-menu li a {
    color: #fd460f!important;
  }
  .dropdown-menu li a:hover {
    background-color: red !important;
  }



.responsive {
  width: 100%;
  max-width: 400px;
  height: auto;
}

.dropbtn {
  background-color: #314FA1;
  color: white;
  padding: 16px;
  font-size: 16px;
  border: none;
}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #314FA1;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown-content a:hover {background-color: #ddd;}

.dropdown:hover .dropdown-content {display: block;}

.dropdown:hover .dropbtn {background-color: #3e8e41;}
  </style>
    <meta charset="UTF-8">
    <title>{% block title %}tv{% endblock %}</title></head>
{% block nav %}

<nav class="navbar navbar-default navbar-fixed-top">
  <a class="navbar-brand" style=" position:relative ;top: -12px" href=""><img src="{% static "logo/TV PNG.png" %}" style="height: 300%; width: auto ;padding-bottom:10%"></a>
  <div>
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      

    </div>
    <div class="collapse navbar-collapse" id="myNavbar">

      <ul class="nav navbar-nav navbar-right" style="font-weight:bold;">
        <li><a href="{% url "package:product_list" %}">HOME</a></li>
        <li><a href="#band">ABOUT US</a></li>
        <li><a href="#contact">CONTACT</a></li>
        <li><a href="{% url "blog:blog_Cntnt" %}">BLOG</a></li>

  
      </ul>
    </div>
  </div>
</nav>{% endblock %}

tv/detaset/blog/templates/product/slids.html
{% extends 'product/base.html' %}
{% load static %}
{% block title %}
    tv
{% endblock %}

{% block content %}
<style type="text/css">
	@keyframes slidy {
0% { left: 0%; }
20% { left: 0%; }
25% { left: -100%; }
45% { left: -100%; }
50% { left: -200%; }
70% { left: -200%; }
75% { left: -300%; }
95% { left: -300%; }
100% { left: -400%; }
}

body { margin: 0; } 
div#slider { overflow: hidden; }
div#slider figure img { width: 20%; float: left; }
div#slider figure { 
  position: relative;
  width: 500%;
  margin: 0;
  left: 0;
  text-align: left;
  font-size: 0;
  animation: 30s slidy infinite; 
}
div.a {
  text-align: center;
}
</style><div>
<div id="slider">
<figure>{% for i in categories %}
<a href="{{ i.get_absolute_url }}"><img src="{% if i.image_slid %}{{i.image_slid.url}}{% endif %}" alt></a>
{% endfor %}
</figure>
</div>
</div>
</div>
<div>
  <div class="container">
    <div class="row">
    {% for i in prices %}
    <div class="col-lg-2 col-sm-4 col-xs-4 a" style="background-color:white;">
     <a href="{{ i.get_absolute_url_price}}"><button>{{i.price_range}}</button></a></div>
    {% endfor %}
    </div>
  </div>
<div class="container-fluid">
   
  <div class="row">
    {% for p in theme %}
    <div class="col-lg-2 col-sm-4 col-xs-4 a" style="background-color:white;">
    <a href="{{ p.get_absolute_url_them}}"> <img src="{% if p.image %}{{p.image.url}}{% endif %}" style="width:50%;height: auto; padding-left: 5px; position:center:"></a><br><h style="position: center" >{{p.name}}</h>
    </div>
     {% endfor %}
  </div>

 
</div>
</div>
    
{% endblock %}